export const MenuFR = [
  { k: "accueil", href: "/" },
  { k: "politique", href: "/politique" },
  { k: "culture", href: "/culture" },
  { k: "economie", href: "/economie" },
  { k: "social", href: "/social" },
  { k: "sport", href: "/sport" },
  { k: "diaspora", href: "/diaspora" },
  { k: "industrie", href: "/industrie" },
  { k: "life-art", href: "/life-art" },
  { k: "environnement", href: "/environnement" },
  { k: "infrastructure", href: "/infrastructure" },
  { k: "tourisme", href: "/tourisme" },
  // { k: "video", href: "/video" },
];
// export const MenuEN = [
//   "home",
//   "policy",
//   "economy",
//   "social",
//   "sport",
//   "diasporat",
//   "industry",
//   "culure",
//   "life art",
//   "environement",
//   "infrastructure",
//   "tourism",
// ];
